
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T08:02:27+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "16fc3388fb40a4ef29ed745af11143ede637234b",
 "version": "0.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
