# Generated by Django 3.2.16 on 2022-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_survey', '0022_auto_20221214_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybooking',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='max_responses',
            field=models.IntegerField(
                default=1,
                help_text='This setting is only applicable if categories are treated as separate sub-surveys',
                verbose_name='Maximal number of responses'
            ),
        ),
        migrations.AddField(
            model_name='categorybooking',
            name='filled_slots',
            field=models.IntegerField(default=1, verbose_name='Number of booked slots'),
        ),
        migrations.AlterField(
            model_name='answergroup',
            name='choices',
            field=models.TextField(
                blank=True,
                help_text="The choices field is only used if the question type\nif the question type is 'radio',\
                        'select',\n'select multiple', or range. For the first 3, please provide\na comma-separated\
                        list of options for this question, for range,\nplease provide a comma-separated list \
                        of min,max,step.",
                null=True,
                verbose_name='Choices'
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(
                blank=True,
                help_text='\n    Order of this question in the display (starting with 1).\n\
                        If none is specified, the question will be shown in a random order\n    ',
                null=True,
                verbose_name='Order'
            ),
        ),
        migrations.AlterField(
            model_name='survey',
            name='save_categories_separately',
            field=models.BooleanField(
                default=False,
                verbose_name='Save data for each category in an independent response \
                        (only if categories are treated as sub-surveys)'
            ),
        ),
    ]
