
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T17:07:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3291335d59c7db3cb9c5e3cc20b4aa0159883d92",
 "version": "0+untagged.1.g3291335"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
