from .pyWrites import write_file
from .pyWrites import append_file
from .pyWrites import read_file
from .pyWrites import read_lines
from .pyWrites import dele_dataset
from .pyJson import write_json
from .pyJson import readteFile
from .pyJson import read_data
from .pyJson import delete_data
from .pyJson import read_whole_file