# Generated by Django 3.1 on 2020-08-18 07:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("scientific_survey", "0013_auto_20200609_0748")]

    operations = [
        migrations.AlterField(
            model_name="question", name="order", field=models.IntegerField(blank=True, null=True, verbose_name="Order")
        ),
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
