# Generated by Django 3.1 on 2020-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("scientific_survey", "0014_auto_20200818_0713")]

    operations = [
        migrations.AddField(
            model_name="response", name="random_seed", field=models.IntegerField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(
                blank=True,
                help_text="If no order is specified, the questions will be shown\nin a random order",
                null=True,
                verbose_name="Order",
            ),
        ),
    ]
