# Generated by Django 3.1 on 2021-01-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scientific_survey", "0017_answergroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="scientific_survey.answergroup",
                verbose_name="Answer group",
            ),
            preserve_default=False,
        ),
    ]
