# Generated by Django 3.1 on 2021-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scientific_survey", "0018_answer_answer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="extra",
            field=models.TextField(blank=True, null=True, verbose_name="Extra"),
        ),
        migrations.AlterField(
            model_name="answergroup",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="""The choices field is only used if the question type
                             if the question type is 'radio', 'select', or
                             'select multiple' provide a comma-separated list of
                             options for this question .""",
                null=True,
                verbose_name="Choices",
            ),
        ),
    ]
