
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-04T15:12:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b37a405cf386785383eb3e0d4f10ddc1f661a20",
 "version": "1.3.8rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
