
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T18:17:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ebeb993e5d6cc24e01dc1dc8be2ae1677d340f6",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
