
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T10:13:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab56addf91c9eca1c942e0c647a0314ae15a7d95",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
