VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('01')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('04')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202402010704
version_date = '2024/02/01 07:04'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
