
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T12:27:24+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "749ef3ff298a94b88c1e67415819fae4fb1de75c",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
