# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cons.ipynb.

# %% auto 0
__all__ = ['CLS', 'NIL', 'ATTR', 'ASSET', 'AREPR', 'BASES', 'DEFAULT', 'IMPORTED', 'NAMESPACE']

# %% ../nbs/00_cons.ipynb 4
#| export


# %% ../nbs/00_cons.ipynb 7
CLS = 'cls'
NIL = ''

ATTR = 'attr'

ASSET = 'asset'
AREPR = 'arepr'
BASES = 'bases'

DEFAULT = 'default'
IMPORTED = 'imported'
NAMESPACE = 'namespace'

# %% ../nbs/00_cons.ipynb 9
_AREPR = f'_{AREPR}'
_ASSET = f'_{ASSET}'
_IMPORTED = f'_{IMPORTED}'

# %% ../nbs/00_cons.ipynb 11
__ANNOTATIONS__ = '__annotations__'
__CALL__ = '__call__'
__DOC__ = '__doc__'
__INIT__ = '__init__'
__NAME__ = '__name__'
__NEW__ = '__new__'
__SIGNATURE__ = 'signature'
