# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_addroot.ipynb.

# %% auto 0
__all__ = ['project_root_path', 'parent']

# %% ../nbs/00_addroot.ipynb 4
import os, sys
from pathlib import Path

project_root_path = None

# %% ../nbs/00_addroot.ipynb 5
parent = str(Path(os.getcwd()).resolve())

while len(parent)>0:
    if os.path.isdir(os.path.join(parent, ".git")):
        project_root_path = parent
        break

    parent, current = os.path.split(parent)
    

# %% ../nbs/00_addroot.ipynb 6
if project_root_path is not None:

    # Add module path to system path.
    if project_root_path not in sys.path:
        sys.path.append(project_root_path)
        print(f"Added {project_root_path} to PATH")
