
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T13:39:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d033cb10b724b922272ca3f4636fb43edaca49b1",
 "version": "2.29.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
