from antlr4 import *
from _typeshed import Incomplete
from io import StringIO as StringIO
from typing import TextIO

def serializedATN(): ...

class vbaLexer(Lexer):
    atn: Incomplete
    decisionsToDFA: Incomplete
    T__0: int
    T__1: int
    T__2: int
    T__3: int
    T__4: int
    T__5: int
    T__6: int
    T__7: int
    ACCESS: int
    ADDRESSOF: int
    ALIAS: int
    AND: int
    ATTRIBUTE: int
    APPACTIVATE: int
    APPEND: int
    AS: int
    BEGIN: int
    BEEP: int
    BINARY: int
    BOOLEAN: int
    BYVAL: int
    BYREF: int
    BYTE: int
    CALL: int
    CASE: int
    CHDIR: int
    CHDRIVE: int
    CLASS: int
    CLOSE: int
    COLLECTION: int
    CONST: int
    DATABASE: int
    DATE: int
    DECLARE: int
    DEFBOOL: int
    DEFBYTE: int
    DEFDATE: int
    DEFDBL: int
    DEFDEC: int
    DEFCUR: int
    DEFINT: int
    DEFLNG: int
    DEFOBJ: int
    DEFSNG: int
    DEFSTR: int
    DEFVAR: int
    DELETESETTING: int
    DIM: int
    DO: int
    DOUBLE: int
    EACH: int
    ELSE: int
    ELSEIF: int
    END_ENUM: int
    END_PROPERTY: int
    END_SELECT: int
    END_TYPE: int
    END_WITH: int
    END: int
    ENUM: int
    EQV: int
    ERASE: int
    ERROR: int
    EVENT: int
    EXIT_DO: int
    EXIT_FOR: int
    EXIT_FUNCTION: int
    EXIT_PROPERTY: int
    EXIT_SUB: int
    FALSE: int
    FILECOPY: int
    FRIEND: int
    FOR: int
    FUNCTION: int
    GET: int
    GLOBAL: int
    GOSUB: int
    GOTO: int
    IF: int
    IMP: int
    IMPLEMENTS: int
    IN: int
    INPUT: int
    IS: int
    INTEGER: int
    KILL: int
    LOAD: int
    LOCK: int
    LONG: int
    LOOP: int
    LEN: int
    LET: int
    LIB: int
    LIKE: int
    LINE_INPUT: int
    LOCK_READ: int
    LOCK_WRITE: int
    LOCK_READ_WRITE: int
    LSET: int
    MACRO_CONST: int
    MACRO_IF: int
    MACRO_ELSEIF: int
    MACRO_ELSE: int
    MACRO_END_IF: int
    ME: int
    MID: int
    MKDIR: int
    MOD: int
    NAME: int
    NEXT: int
    NEW: int
    NOT: int
    NOTHING: int
    NULL_: int
    ON: int
    ON_ERROR: int
    ON_LOCAL_ERROR: int
    OPEN: int
    OPTIONAL: int
    OPTION_BASE: int
    OPTION_EXPLICIT: int
    OPTION_COMPARE: int
    OPTION_PRIVATE_MODULE: int
    OR: int
    OUTPUT: int
    PARAMARRAY: int
    PRESERVE: int
    PRINT: int
    PRIVATE: int
    PROPERTY_GET: int
    PROPERTY_LET: int
    PROPERTY_SET: int
    PTRSAFE: int
    PUBLIC: int
    PUT: int
    RANDOM: int
    RANDOMIZE: int
    RAISEEVENT: int
    READ: int
    READ_WRITE: int
    REDIM: int
    REM: int
    RESET: int
    RESUME: int
    RETURN: int
    RMDIR: int
    RSET: int
    SAVEPICTURE: int
    SAVESETTING: int
    SEEK: int
    SELECT: int
    SENDKEYS: int
    SET: int
    SETATTR: int
    SHARED: int
    SINGLE: int
    SPC: int
    STATIC: int
    STEP: int
    STOP: int
    STRING: int
    SUB: int
    TAB: int
    TEXT: int
    THEN: int
    TIME: int
    TO: int
    TRUE: int
    TYPE: int
    TYPEOF: int
    UNLOAD: int
    UNLOCK: int
    UNTIL: int
    VARIANT: int
    VERSION: int
    WEND: int
    WHILE: int
    WIDTH: int
    WITH: int
    WITHEVENTS: int
    WRITE: int
    XOR: int
    AMPERSAND: int
    ASSIGN: int
    DIV: int
    EQ: int
    GEQ: int
    GT: int
    LEQ: int
    LPAREN: int
    LT: int
    MINUS: int
    MINUS_EQ: int
    MULT: int
    NEQ: int
    PLUS: int
    PLUS_EQ: int
    POW: int
    RPAREN: int
    L_SQUARE_BRACKET: int
    R_SQUARE_BRACKET: int
    GUID: int
    STRINGLITERAL: int
    OCTLITERAL: int
    HEXLITERAL: int
    SHORTLITERAL: int
    INTEGERLITERAL: int
    DOUBLELITERAL: int
    DATELITERAL: int
    LINE_CONTINUATION: int
    NEWLINE: int
    REMCOMMENT: int
    COMMENT: int
    SINGLEQUOTE: int
    COLON: int
    UNDERSCORE: int
    WS: int
    IDENTIFIER: int
    channelNames: Incomplete
    modeNames: Incomplete
    literalNames: Incomplete
    symbolicNames: Incomplete
    ruleNames: Incomplete
    grammarFileName: str
    def __init__(self, input: Incomplete | None = None, output: TextIO = ...) -> None: ...
