
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T10:50:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fb3f3255e50b3a05dbee407161889a153596a77",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
