# Generated by Django 3.0.5 on 2024-02-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsToVerifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('db_external_name', models.CharField(blank=True, max_length=400, null=True)),
                ('should_verify', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('started_at', models.DateField(auto_now_add=True)),
                ('finished_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('apps', models.ManyToManyField(blank=True, null=True, related_name='users', to='alegriadb.AppsToVerifyModel')),
            ],
        ),
    ]
