# Generated by Django 3.0.5 on 2024-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alegriadb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verified',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
