# Generated by Django 3.0.5 on 2024-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alegriadb', '0002_auto_20240201_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verified',
            name='finished_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verified',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
