# Generated by Django 3.0.5 on 2024-02-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alegriadb', '0003_auto_20240201_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectemail',
            name='apps',
        ),
    ]
