
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T13:45:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d40db5548e921e1019292bd18e0fb195c4c7507",
 "version": "v4.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
