# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.03.232712'

RELEASE_GIT_HEAD = 'e3ce2b385ec1f03fac9d4210c57fda77134495fc'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.02.03.232712dev'
