
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T16:28:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d5e7609138469c2a654f4467eec320095ee1623",
 "version": "2.29.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
