
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/ol_openedx_otel_monitoring:otel_monitoring_package

from setuptools import setup

setup(**{
    'description': 'OTel Monitoring',
    'entry_points': {
        'lms.djangoapp': [
            'ol_openedx_otel_monitoring = ol_openedx_otel_monitoring.apps:OTelMonitoringConfig',
        ],
        'cms.djangoapp': [
            'ol_openedx_otel_monitoring = ol_openedx_otel_monitoring.apps:OTelMonitoringConfig',
        ],
    },
    'install_requires': (
        'Django>2.0',
        'edx-django-utils>4.0.0',
        'opentelemetry-distro',
        'opentelemetry-exporter-otlp-proto-http',
        'opentelemetry-exporter-richconsole',
        'opentelemetry-instrumentation-django',
    ),
    'license': 'BSD-3-Clause',
    'name': 'ol-openedx-otel-monitoring',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        '',
        'ol_openedx_otel_monitoring',
        'ol_openedx_otel_monitoring.settings',
    ),
    'python_requires': '>=3.8',
    'version': '0.1.1',
})
