
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T01:26:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1afed4edaeed1d4b3483c60c0b3d8595198b863b",
 "version": "3.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
