VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('31')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('18')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202401311818
version_date = '2024/01/31 18:18'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
