
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T16:05:49+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfbe5bad735fcd810ecdf834b944a046cb565796",
 "version": "0.8.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
