
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-04T20:30:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "14343aaae46ebb15551aa116221b1e91c9cf4b96",
 "version": "0.0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
