"""Declare all global constants."""

COMMANDS = {
    "start": "Restart bot",
    "id": "Get details ID of a message",
    "get": "Forward any posts from public channel",
    "help": "Learn usage",
    "report": "Send a message to the bot Admin",
}

REGISTER_COMMANDS = True

KEEP_LAST_MANY = 10000

CONFIG_FILE_NAME = "tgcf.config.json"
CONFIG_ENV_VAR_NAME = "TGCF_CONFIG"

MONGO_DB_NAME = "tgcf-config"
MONGO_COL_NAME = "tgcf-instance-0"

BOT_CONFIG_FILE_NAME = "bot.config.json"
BOT_CONFIG_ENV_VAR_NAME = "TGCF_BOT_CONFIG"

TAGS = {
    "general/other": "総合・その他",
    "with_lines": "セリフ付き",
    "immediate_removal": "即抜き",
    "women's_changing_room": "女子更衣室",
    "body_pillow_cover": "抱き枕カバー",
    "full_moon": "満月",
    "original_ai_illustration": "オリジナルaiイラスト",
    "ai_erotic_illustration_miscellaneous": "aiエロイラスト雑多",
    "butt_sticking_out": "お尻突き出し",
    "jiangshi_girl": "キョンシー娘",
    "cyber_punk": "サイバーパンク",
    "santa_costume": "サンタコス",
    "dancer": "ダンサー",
    "china_dress": "チャイナドレス",
    "himiko_toga": "トガヒミコ",
    "nurse": "ナース",
    "high_school_girl_without_panties": "ノーパン女子高生",
    "flandre_scarlet": "フランドール・スカーレット",
    "makima": "マキマ",
    "loli_paradise": "ロリパラダイス",
    "disheveled_clothes": "乱れた服",
    "hatsune_miku": "初音ミク",
    "kaguya_shinomiya": "四宮かぐや",
    "forgetful_high_school_girl": "忘れんぼ女子高生",
    "clothing_defects": "衣服の不具合",
    "naked_women": "裸の女性複数",
    "tentacle_rape": "触手レイプ",
    "see-through_dress": "透け透けワンピース",
    "rain_exposure": "雨露出",
    "snow_exposure": "雪露出",
    "atmosphere_precure": "雰囲気プリキュア",
    "loli": "ロリ",
    "bath_loli": "お風呂ロリ",
    "no_panties_loli": "ノーパンロリ",
    "loli_masturbation": "ロリオナニー",
    "loli_big_breasts": "ロリ巨乳",
    "carefully_selected_loli": "厳選ロリ",
    "kimono_loli": "着物ロリ",
    "naked_school_bag": "裸ランドセル",
    "small_breasts/small_breasts": "貧乳・ちっぱい",
    "pants/no_panties": "パンツ・ノーパン",
    "crouching_panty_shot": "しゃがみパンチラ",
    "probably_not_wearing_it": "たぶんはいてない",
    "skirt_peeping": "スカート覗き",
    "no_panties_tucked_up": "ノーパンたくし上げ",
    "no_panties_garter_belt": "ノーパンガーターベルト",
    "high_kick": "ハイキック",
    "pants_down": "パンツ下ろし",
    "half_off_pants": "パンツ半脱ぎ",
    "offer_panties": "パンツ差し出し",
    "pants_sideways": "パンツ横ずらし",
    "wedgies_in_pants": "パンツ食い込み",
    "fix_your_pants": "パンツ食い込み直し",
    "bottomless/bottomless": "下脱ぎ・ボトムレス",
    "naked_t-shirt": "裸にｔシャツ",
    "open_leg_panty_shot": "開脚パンチラ",
    "wind_no_panties": "風ノーパン",
    "wind_panchira": "風パンチラ",
    "breasts/nipples": "おっぱい・乳首",
    "breast_pecking": "おっぱいつつき",
    "grabbing_breasts": "おっぱい掴み",
    "breasts_through_glass": "ガラス越しおっぱい",
    "see-through_without_bra": "ノーブラ透け",
    "lesbian_nipple_sucking": "レズ乳首吸い",
    "breast_feeding_tray": "乗せ乳トレイ",
    "breast_matching": "乳合わせ",
    "clothes_with_hollowed_out_nipples": "乳首くり抜き服",
    "nipple_slip": "乳首チラ",
    "nipple_piercing": "乳首ピアス",
    "nipple_alignment": "乳首合わせ",
    "nipple_picking": "乳首摘み",
    "hand_bra": "手ブラ",
    "breastfeeding_handjob": "授乳手コキ",
    "breasts_exposed_through_clothes": "服からおっぱい露出",
    "sucking_breast_milk": "母乳吸い取り",
    "breast_milk_injection": "母乳噴射",
    "one_breast_exposed": "片乳露出",
    "beautiful_breasts": "美乳",
    "fondling_one's_own_breasts": "自分の乳揉み",
    "butt/anal": "お尻・アナル",
    "anal_toying": "アナルいじり",
    "anal_tail": "アナル尻尾",
    "anal_waiting": "アナル待機",
    "anal_foreign_object_insertion": "アナル異物挿入",
    "wall_ass": "壁尻",
    "butt_up": "尻アップ",
    "vibrators/sex_toys": "バイブ・性具",
    "toy_double_penetration": "おもちゃ二穴挿入",
    "clitoris_rotor": "クリトリスローター",
    "lesbian_toys": "レズおもちゃ",
    "preparation_vibe": "仕込みバイブ",
    "vibrator_remote_control_on_thigh": "太ももにバイブリモコン",
    "restraint_vibrator": "拘束バイブ",
    "shame/exposure": "羞恥・露出",
    "naked_beach": "全裸ビーチ",
    "public_exposure": "公然露出",
    "school_exposure": "学校露出",
    "doxxer": "晒し者",
    "forest_exposure": "森露出",
    "instant_exposure": "瞬間露出",
    "crucifixion": "磔刑",
    "naked_coat_slut": "裸コート痴女",
    "naked_raincoat": "裸レインコート",
    "outdoor_urination": "野外放尿",
    "play/act": "プレイ・行為",
    "pee_maid": "おしっこメイド",
    "crouching_urination": "しゃがみ放尿",
    "pile_back": "マンぐり返し",
    "creampie": "中出し",
    "seduction_of_girls": "女の子たちの誘惑",
    "sex_education": "性教育",
    "photograph": "撮影",
    "standing_back": "立ちバック",
    "consultation": "診察",
    "footjob": "足コキ",
    "character": "キャラクター",
    "ol": "ol",
    "maid": "メイド",
    "girl_with_glasses": "メガネっ娘",
    "nun_(sister)": "修道女（シスター）",
    "high_school_girl": "女子高生",
    "high_school_girl_crawling_on_all_fours": "女子高生の四つん這い",
    "high_school_girl_thighs": "女子高生の太もも",
    "schoolgirl_masturbation": "女子高生オナニー",
    "female_pirate": "女海賊",
    "giant_girl": "巨大娘",
    "moe/soft_erotic": "萌え・ソフトエロ",
    "school_swimwear": "スクール水着",
    "pocari_sweat": "ポカリスエット",
    "waking_up": "寝起き",
    "stripped_photoshop": "剥ぎコラ",
    "bdsm": "bdsm",
    "human_furniture": "人間家具",
    "dogeza": "土下座",
    "forced_spread_legs": "強制開脚",
    "restraint_tickling": "拘束くすぐり",
    "restraint_lifting": "拘束吊し上げ",
    "machine_fucking": "機械姦",
    "hakoiri_musume": "箱入り娘",
    "meat_urinal": "肉便器",
    "tentacle_plants": "触手植物",
    "collar/female_dog": "首輪・メス犬",
    "pussy/clitoris": "おまんこ・クリトリス",
    "eating_with_a_pussy": "おまんこで食事",
    "kupaa": "くぱぁ",
    "kupaa_precure": "くぱぁプリキュア",
    "clitoral_erection": "クリトリス勃起",
    "low_angle_spread": "ローアングルくぱぁ",
    "masturbation": "オナニー",
    "hand_in_pants": "パンツの中に手",
    "fingering_masturbation": "手マンオナニー",
    "horny_ona": "角オナ",
    "lesbian/yuri": "レズ・百合",
    "lesbian_cunnilingus": "レズクンニ",
    "lesbian_orgy": "レズ乱交",
    "lesbian_fingering": "レズ手マン",
    "double_headed_dildo": "双頭ディルド",
    "naked○○": "裸で○○",
    "body_paint": "ボディペイント",
    "naked_with_weapons": "裸で武器",
    "naked_apron": "裸エプロン",
    "naked_shirt": "裸シャツ",
    "naked_sports": "裸スポーツ",
    "naked_knee_socks": "裸ニーソ",
    "naked_bath_towel": "裸バスタオル",
    "naked_boots": "裸ブーツ",
    "naked_muffler": "裸マフラー",
    "naked_cloak": "裸マント",
    "naked_ribbon": "裸リボン",
    "naked_bandage": "裸包帯",
    "mischief/erotic_happenings": "いたずら・エロハプニング",
    "my_cheeks_tingle_with_chin": "チンでほっぺツンツン",
    "swimsuit_that_came_off": "外れた水着",
    "sexual_prank": "性的イタズラ",
    "costume": "コスチューム",
    "wedding_dress": "ウエディングドレス",
    "erotic_costumes": "エロ衣装",
    "cheerleader": "チアガール",
    "halloween": "ハロウィン",
    "bunny_girl": "バニーガール",
    "pie_slash": "パイスラッシュ",
    "bikini_armor": "ビキニアーマー",
    "bloomers/gym_clothes": "ブルマ・体操服",
    "body_suit": "ボディスーツ",
    "micro_bikini": "マイクロビキニ",
    "loose_socks": "ルーズソックス",
    "front_adhesive_plaster": "前貼り絆創膏",
    "japanese_clothes": "和服",
    "shrine_maiden": "巫女",
    "the_sweater_that_kills_virginity": "童貞を殺すセーター",
    "reverse_bunny": "逆バニー",
    "fetish_maniac": "フェチ・マニアック",
    "one_shota": "おねショタ",
    "ahegao_w_peace": "アヘ顔wピース",
    "erotic_photo/selfie": "エロ写メ・自撮り",
    "jack_o_challenge": "ジャック・オーチャレンジ",
    "fight_for_cock": "チンポ取り合い",
    "torn_pantyhose": "パンスト破れ",
    "pole_dance": "ポールダンス",
    "one_finger_selfie": "ワンフィンガーセルフィー",
    "lift_both_legs": "両足抱え持ち上げ",
    "condom_in_mouth": "咥えコンドーム",
    "sunburn_mark": "日焼け跡",
    "underwater_erotic_images": "水中エロ画像",
    "water_play": "水遊び",
    "squirting": "潮吹き",
    "wet_and_transparent": "濡れ透け",
    "crossed_legs_thighs": "脚組み太もも",
    "armpit_erotic": "腋エロ",
    "bicycle": "自転車",
    "lots_of_naked_women": "裸の女性大量",
    "y-shaped/i-shaped_spread_legs": "ｙ字・ｉ字開脚"
}