# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/addroot',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/addroot',
                'lib_path': 'addroot'},
  'syms': {'addroot.addgitroot': {'addroot.addgitroot.find_root': ('addroot.html#find_root', 'addroot/addgitroot.py')}}}
