# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.31.232703'

RELEASE_GIT_HEAD = 'fc2cc626f07328a6c71b5e21853e4cfa7b1e6256'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.01.31.232703dev'
