
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T16:04:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc00f57bec791743e61727ce184b43f45e84a0a5",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
