
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T16:31:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58797b1e8d653f1fff6f23ed57e8cfb5638120ba",
 "version": "3.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
