VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('29')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('52')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202401292152
version_date = '2024/01/29 21:52'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
