
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T11:12:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2958f30ddc2d629f2720ff7c0d17793fc314189",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
