
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T17:50:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e976567edf3c21a3181df519ada9066e057819d1",
 "version": "2.3.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
