# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/addroot',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/addroot',
                'lib_path': 'addroot'},
  'syms': {'addroot.addroot': {}, 'addroot.core': {'addroot.core.foo': ('core.html#foo', 'addroot/core.py')}}}
