
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-04T02:11:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6050987c68026b37acdd2c1e4b2f00dc7ea7b44",
 "version": "1.4.dev2405"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
