
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-26T15:17:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d084f431e7f8d592ba200dafe3d7875976d57d38",
 "version": "24.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
