
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-03T14:09:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf3ec5683ec0eea3baf1c700a8df751b57cd3b86",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
