# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/server_deployment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from resemble.v1alpha1 import kubernetes_helpers_pb2 as resemble_dot_v1alpha1_dot_kubernetes__helpers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)resemble/v1alpha1/server_deployment.proto\x12\x11resemble.v1alpha1\x1a*resemble/v1alpha1/kubernetes_helpers.proto\"\x80\x05\n\x10ServerDeployment\x12:\n\x06status\x18\x01 \x01(\x0b\x32*.resemble.v1alpha1.ServerDeployment.Status\x12\x36\n\x04spec\x18\x02 \x01(\x0b\x32(.resemble.v1alpha1.ServerDeployment.Spec\x1a\xd1\x03\n\x06Status\x12\x43\n\x06\x66\x61iled\x18\x01 \x01(\x0b\x32\x31.resemble.v1alpha1.ServerDeployment.Status.FailedH\x00\x12M\n\x0b\x63onfiguring\x18\x02 \x01(\x0b\x32\x36.resemble.v1alpha1.ServerDeployment.Status.ConfiguringH\x00\x12K\n\nconfigured\x18\x03 \x01(\x0b\x32\x35.resemble.v1alpha1.ServerDeployment.Status.ConfiguredH\x00\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x36\n\rserver_config\x18\x05 \x01(\x0b\x32\x1f.resemble.v1alpha1.V1ObjectMeta\x1a=\n\x06\x46\x61iled\x12\x33\n\nconfig_pod\x18\x01 \x01(\x0b\x32\x1f.resemble.v1alpha1.V1ObjectMeta\x1a\x42\n\x0b\x43onfiguring\x12\x33\n\nconfig_pod\x18\x01 \x01(\x0b\x32\x1f.resemble.v1alpha1.V1ObjectMeta\x1a\x0c\n\nConfiguredB\r\n\x0bstate_oneof\x1a$\n\x04Spec\x12\x1c\n\x14\x63ontainer_image_name\x18\x01 \x01(\tb\x06proto3')



_SERVERDEPLOYMENT = DESCRIPTOR.message_types_by_name['ServerDeployment']
_SERVERDEPLOYMENT_STATUS = _SERVERDEPLOYMENT.nested_types_by_name['Status']
_SERVERDEPLOYMENT_STATUS_FAILED = _SERVERDEPLOYMENT_STATUS.nested_types_by_name['Failed']
_SERVERDEPLOYMENT_STATUS_CONFIGURING = _SERVERDEPLOYMENT_STATUS.nested_types_by_name['Configuring']
_SERVERDEPLOYMENT_STATUS_CONFIGURED = _SERVERDEPLOYMENT_STATUS.nested_types_by_name['Configured']
_SERVERDEPLOYMENT_SPEC = _SERVERDEPLOYMENT.nested_types_by_name['Spec']
ServerDeployment = _reflection.GeneratedProtocolMessageType('ServerDeployment', (_message.Message,), {

  'Status' : _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {

    'Failed' : _reflection.GeneratedProtocolMessageType('Failed', (_message.Message,), {
      'DESCRIPTOR' : _SERVERDEPLOYMENT_STATUS_FAILED,
      '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
      # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment.Status.Failed)
      })
    ,

    'Configuring' : _reflection.GeneratedProtocolMessageType('Configuring', (_message.Message,), {
      'DESCRIPTOR' : _SERVERDEPLOYMENT_STATUS_CONFIGURING,
      '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
      # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment.Status.Configuring)
      })
    ,

    'Configured' : _reflection.GeneratedProtocolMessageType('Configured', (_message.Message,), {
      'DESCRIPTOR' : _SERVERDEPLOYMENT_STATUS_CONFIGURED,
      '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
      # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment.Status.Configured)
      })
    ,
    'DESCRIPTOR' : _SERVERDEPLOYMENT_STATUS,
    '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
    # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment.Status)
    })
  ,

  'Spec' : _reflection.GeneratedProtocolMessageType('Spec', (_message.Message,), {
    'DESCRIPTOR' : _SERVERDEPLOYMENT_SPEC,
    '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
    # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment.Spec)
    })
  ,
  'DESCRIPTOR' : _SERVERDEPLOYMENT,
  '__module__' : 'resemble.v1alpha1.server_deployment_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ServerDeployment)
  })
_sym_db.RegisterMessage(ServerDeployment)
_sym_db.RegisterMessage(ServerDeployment.Status)
_sym_db.RegisterMessage(ServerDeployment.Status.Failed)
_sym_db.RegisterMessage(ServerDeployment.Status.Configuring)
_sym_db.RegisterMessage(ServerDeployment.Status.Configured)
_sym_db.RegisterMessage(ServerDeployment.Spec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERDEPLOYMENT._serialized_start=109
  _SERVERDEPLOYMENT._serialized_end=749
  _SERVERDEPLOYMENT_STATUS._serialized_start=246
  _SERVERDEPLOYMENT_STATUS._serialized_end=711
  _SERVERDEPLOYMENT_STATUS_FAILED._serialized_start=553
  _SERVERDEPLOYMENT_STATUS_FAILED._serialized_end=614
  _SERVERDEPLOYMENT_STATUS_CONFIGURING._serialized_start=616
  _SERVERDEPLOYMENT_STATUS_CONFIGURING._serialized_end=682
  _SERVERDEPLOYMENT_STATUS_CONFIGURED._serialized_start=684
  _SERVERDEPLOYMENT_STATUS_CONFIGURED._serialized_end=696
  _SERVERDEPLOYMENT_SPEC._serialized_start=713
  _SERVERDEPLOYMENT_SPEC._serialized_end=749
# @@protoc_insertion_point(module_scope)
