
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T18:39:10+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "aa1e87e0e579bf35358c2214ec219f729275d78f",
 "version": "0.7.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
