
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T16:30:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a8c6373c769ad9e75b23ed7f5173e279cf4cfc5",
 "version": "2.14.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
