
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T09:32:17-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec5c1203089d701275ce2c86546dc25b837d47b",
 "version": "2.29.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
