# coding: utf-8

# flake8: noqa

"""
    Developer API - URLR

    API powering the features of URLR.

    The version of the OpenAPI document: 0.2
    Contact: contact@urlr.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.1"

# import apis into sdk package
from urlr.api.authentification_api import AuthentificationApi
from urlr.api.link_api import LinkApi
from urlr.api.stats_api import StatsApi

# import ApiClient
from urlr.api_response import ApiResponse
from urlr.api_client import ApiClient
from urlr.configuration import Configuration
from urlr.exceptions import OpenApiException
from urlr.exceptions import ApiTypeError
from urlr.exceptions import ApiValueError
from urlr.exceptions import ApiKeyError
from urlr.exceptions import ApiAttributeError
from urlr.exceptions import ApiException

# import models into sdk package
from urlr.models.authentification200_response import Authentification200Response
from urlr.models.authentification401_response import Authentification401Response
from urlr.models.authentification_request import AuthentificationRequest
from urlr.models.reduce_link200_response import ReduceLink200Response
from urlr.models.reduce_link400_response import ReduceLink400Response
from urlr.models.reduce_link_request import ReduceLinkRequest
from urlr.models.stats200_response import Stats200Response
from urlr.models.stats400_response import Stats400Response
from urlr.models.stats_request import StatsRequest
