from __future__ import annotations
MAPPING_TYPE_ERROR = {
    'ADJ': 'ADJECTIVE_CHOICE',
    'ADJ:FORM': 'ADJECTIVE_FORM',
    'ADV': 'ADVERB',
    'CONJ': 'CONJUNCTION',
    'CONTR': 'CONTRACTION',
    'DET': 'DETERMINER',
    'MORPH': 'MORPHOLOGY',
    'NOUN': 'NOUN_CHOICE',
    'NOUN:INFL': 'NOUN_INFLECTION',
    'NOUN:NUM': 'NOUN_NUMBER',
    'NOUN:POSS': 'POSSESSIVE_NOUN',
    'ORTH': 'SPELLING',
    'OTHER': 'OTHER',
    'PART': 'PARTICLE',
    'PREP': 'PREPOSITION',
    'PRON': 'PRONOUN',
    'PUNCT': 'PUNCTUATION',
    'SPELL': 'SPELLING',
    'VERB': 'VERB_CHOICE',
    'VERB:FORM': 'VERB_FORM',
    'VERB:INFL': 'VERB_INFLECTION',
    'VERB:SVA': 'SUBJECT_VERB_AGREEMENT',
    'VERB:TENSE': 'VERB_TENSE',
    'WO': 'WORD_ORDER',
    'UNK': 'OTHER'
}


MAPPING_ERRANT_ACA = {
    'ADJ': 'Word Choice',
    'ADJ:FORM': 'Word Form',
    'ADV': 'Word Form',
    'CONJ': 'Linking Devices',
    'CONTR': 'Informal',
    'DET': 'Article',
    'MORPH': 'Word Form',
    'NOUN': 'Word Choice',
    'NOUN:INFL': 'Plural-Singular',
    'NOUN:NUM': 'Plural-Singular',
    'NOUN:POSS': 'Word Form',
    'ORTH': 'Spelling',
    'OTHER': 'Other',
    'PART': 'Word Form',
    'PREP': 'Preposition',
    'PRON': 'Word Form',
    'PUNCT': 'Punctuation',
    'SPELL': 'Spelling',
    'VERB': 'Word Choice',
    'VERB:FORM': 'Verb Form',
    'VERB:INFL': 'Verb Tense',
    'VERB:SVA': 'Subject Verb Agreement',
    'VERB:TENSE': 'Verb Tense',
    'WO': 'Word Order',
}
