
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T22:36:12+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "b9c5f3fcfdb0452e80095ec85b0aff4c91cbfa33",
 "version": "0.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
