
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T20:38:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac6cd9f868948cdfb77407f375d5fdd47de0c116",
 "version": "2.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
