
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T20:57:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a19be73a8b12d1fc88a0e9f03b4cf30b8ece8d1",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
