# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cdg_jsonld_arbitre import CdgJsonldArbitre  # noqa: E501
from swagger_client.rest import ApiException


class TestCdgJsonldArbitre(unittest.TestCase):
    """CdgJsonldArbitre unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCdgJsonldArbitre(self):
        """Test CdgJsonldArbitre"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cdg_jsonld_arbitre.CdgJsonldArbitre()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
