# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cdg_jsonld_equipe import CdgJsonldEquipe  # noqa: E501
from swagger_client.rest import ApiException


class TestCdgJsonldEquipe(unittest.TestCase):
    """CdgJsonldEquipe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCdgJsonldEquipe(self):
        """Test CdgJsonldEquipe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cdg_jsonld_equipe.CdgJsonldEquipe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
