
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T11:25:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "87de1b63c820cd3d3991f84609e8e8d5fc460c33",
 "version": "2.3.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
