
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-04T18:25:41+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "de7c0a714cd0550d27824a9030f087bbcd8f0a95",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
