
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-03T14:30:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "263dd1a08a72bc824c7f6f2869f341c954f8ac3b",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
