
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-01T05:41:08-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b5ef1f56961aef67ca269cecb3282c9f1aa628f",
 "version": "5.4.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
