# coding: utf-8
# Generated by setup.py for PyCBC on 2024-02-02 13:59:02 +0000.

# general info
version = '2.3.4'
date = '2024-02-02 12:43:16 +0000'
release = 'True'
last_release = '2.4.0'

# git info
git_hash = '1c1a91aa3f602d79717175c04d993a502b7e0dbb'
git_branch = 'None'
git_tag = 'v2.3.4'
git_author = 'Ian Harry <ian.harry@ligo.org>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2024-02-02 13:59:02 +0000'
git_verbose_msg = """Version: 2.3.4
Branch: None
Tag: v2.3.4
Id: 1c1a91aa3f602d79717175c04d993a502b7e0dbb
Builder: Unknown User <>
Build date: 2024-02-02 13:59:02 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
