# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Outsource Work",
    "version": "14.0.1.14.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "website",
        "ssi_financial_accounting",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_duration_mixin",
        "ssi_product_line_account_mixin",
        "ssi_transaction_pricelist_mixin",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/approval_template_data.xml",
        "data/policy_template_data.xml",
        "menu.xml",
        "templates/outsource_work_mixin_templates.xml",
        "views/ir_model_views.xml",
        "views/outsource_work_type_category_views.xml",
        "views/outsource_work_type_views.xml",
        "views/outsource_work_views.xml",
        "views/outsource_work_portal_templates.xml",
        "views/outsource_work_outstanding_type_views.xml",
        "views/outsource_work_outstanding_views.xml",
        "views/outsource_work_outstanding_batch_views.xml",
        "views/outsource_work_outstanding_portal_templates.xml",
    ],
    "demo": [],
}
