# Generated by Django 5.0.1 on 2024-02-01 15:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosteladata',
            name='chatbox',
        ),
        migrations.RemoveField(
            model_name='prosteladata',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='prosteladata',
            name='section',
        ),
        migrations.RemoveField(
            model_name='prosteladata',
            name='storage_data',
        ),
        migrations.RemoveField(
            model_name='prosteladata',
            name='title',
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='asst_id',
            field=models.CharField(default='No ID', max_length=150),
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='asst_name',
            field=models.CharField(default='No name', max_length=250),
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='code_inter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='instructions',
            field=models.CharField(default='No instructions', max_length=250),
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='retrieval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosteladata',
            name='thread',
            field=models.CharField(default='Empty', max_length=150),
        ),
        migrations.AlterField(
            model_name='billingrecipt',
            name='option',
            field=models.CharField(choices=[('budget_marketing', 'Budget Marketing'), ('Others', 'Others'), ('Billing receipt', 'Billing receipt'), ('budget_development', 'Budget Development'), ('Monthly charge', 'Monthly charge'), ('budget_design', 'Budget Design')], max_length=60, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business',
            field=models.CharField(blank=True, choices=[('E-commerce', 'E-commerce'), ('Consulting', 'Consulting'), ('Repair and Maintenance Services', 'Repair and Maintenance Services'), ('Beauty and Personal Care Services', 'Beauty and Personal Care Services'), ('Media Creators', 'Media Creators'), ('Restaurants and Food Services', 'Restaurants and Food Services'), ('Health and Wellness', 'Health and Wellness'), ('Logistics and Transportation Services', 'Logistics and Transportation Services'), ('Marketing and Advertising Services', 'Marketing and Advertising Services'), ('Education and Training', 'Education and Training'), ('IT Development Services', 'IT Development Services')], max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='card',
            field=models.CharField(blank=True, choices=[('card-light-danger', 'card-light-danger'), ('card-dark-blue', 'card-dark-blue'), ('card-light-blue', 'card-light-blue'), ('card-tale', 'card-tale')], max_length=50, null=True, verbose_name='Color Card'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, choices=[('Advices', 'Advices'), ('Events', 'Events'), ('Resources', 'Resources'), ('News', 'News'), ('Interviews', 'Interviews'), ('Stories', 'Stories')], default='News', max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookpagecomments',
            name='update_rate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 12, 38, 33, 209413)),
        ),
        migrations.AlterField(
            model_name='itemdiscount',
            name='field',
            field=models.CharField(choices=[('Promotional Discount', 'Promotional Discount'), ('No Selected', 'No Selected'), ('Initial Payment', 'Initial Payment'), ('Stela Payment Free Suscription', 'Stela Payment Free Suscription')], max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.CharField(choices=[('Cloud Elastic Instance', 'Cloud Elastic Instance'), ('Stela Design', 'Stela Design'), ('No Selected', 'No Selected'), ('Stela Marketing', 'Stela Marketing'), ('Stela Websites', 'Stela Websites'), ('Store', 'Store'), ('Cloud Domains', 'Cloud Domains')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathcontrol',
            name='step',
            field=models.CharField(choices=[('Step 2', 'Step 2'), ('Step 3', 'Step 3'), ('Step 4', 'Step 4')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitepolicy',
            name='section',
            field=models.CharField(blank=True, choices=[('budget_design_terms', 'Budget Design Terms'), ('Terms and Conditions', 'Terms and Conditions'), ('budget_development_terms', 'Budget Development Terms'), ('Disclaimer', 'Disclaimer'), ('Cookie Policy', 'Cookie Policy'), ('billing_terms', 'Monthly Billing Terms'), ('budget_marketing_terms', 'Budget Marketing Terms'), ('monthly_terms', 'Billing Terms'), ('Return Policy', 'Return Policy'), ('Privacy Policy', 'Privacy Policy')], default='Terms and Conditions', max_length=150),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('X', 'X'), ('Youtube', 'Youtube'), ('Github', 'Github'), ('Facebook', 'Facebook'), ('Wikipedia', 'Wikipedia'), ('Tiktok', 'Tiktok'), ('Linkedin', 'Linkedin')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Zelle', 'Zelle'), ('Binance', 'Binance'), ('Paypal', 'Paypal')], max_length=100, verbose_name='Type of Wallet'),
        ),
        migrations.CreateModel(
            name='ProStelaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('asst_message', models.TextField()),
                ('in_tokens', models.IntegerField(default=0)),
                ('out_tokens', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbox', to='stela_control.prosteladata')),
            ],
        ),
        migrations.DeleteModel(
            name='ProStelaUsage',
        ),
    ]
