
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-02T17:56:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b68ab824031cfefee693c7821973824a50b3367",
 "version": "0.15.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
